# Generated by Django 5.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_vw_ultima_posicion_nino'),
        ('children', '__first__'),
        ('zones', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinoZonaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentro', models.BooleanField(db_column='dentro', help_text='True if the child was inside the zone at the last evaluation.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='estados_zona', to='children.nino')),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, related_name='estados_nino', to='zones.zonasegura')),
            ],
            options={
                'db_table': 'nino_zona_estado',
                'indexes': [
                    models.Index(fields=['id_nino', 'dentro'], name='ix_nze_nino_dentro'),
                ],
                'unique_together': {('id_nino', 'id_zona')},
            },
        ),
    ]
