# Generated by Django 5.2.15 on 2026-07-05 18:53

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='nombre_rol', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('correo', models.EmailField(db_column='correo', max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=256)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
                ('intentos_fallidos', models.PositiveIntegerField(db_column='intentos_fallidos', default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, db_column='bloqueado_hasta', null=True)),
                ('fecha_ultimo_cambio_password', models.DateTimeField(blank=True, db_column='fecha_ultimo_cambio_password', null=True)),
                ('requiere_cambio_password', models.BooleanField(db_column='requiere_cambio_password', default=False)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modificado_por', models.ForeignKey(blank=True, db_column='modificado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', apps.accounts.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraAcceso',
            fields=[
                ('id_bitacora_acceso', models.AutoField(db_column='id_bitacora_acceso', primary_key=True, serialize=False)),
                ('correo_intento', models.CharField(db_column='correo_intento', max_length=150)),
                ('tipo_evento', models.CharField(choices=[('login_exitoso', 'Login exitoso'), ('login_fallido', 'Login fallido'), ('logout', 'Logout')], db_column='tipo_evento', max_length=20)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, db_column='direccion_ip', null=True)),
                ('user_agent', models.CharField(blank=True, db_column='user_agent', max_length=300, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, db_column='fecha_evento')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora_acceso',
            },
        ),
    ]
