# Generated by Django 5.2.15 on 2026-07-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tutor'),
        ('accounts', '0003_usuario_public_id'),
    ]

    operations = [
    ]
