# Generated by Django 5.2.15 on 2026-07-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_nino_foto_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPareo',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('id_codigo_pareo', models.AutoField(db_column='id_codigo_pareo', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='codigo', max_length=6, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('expira_en', models.DateTimeField(db_column='expira_en')),
                ('usado', models.BooleanField(db_column='usado', default=False)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_pareo', to='children.nino')),
                ('id_tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_pareo', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, db_column='modificado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codigo_pareo',
                'indexes': [models.Index(fields=['codigo'], name='ix_codigo_pareo_codigo'), models.Index(fields=['id_nino', 'usado'], name='ix_codigo_pareo_nino_usado')],
            },
        ),
    ]
