# Generated by Django 5.2.15 on 2026-07-07 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_tutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('id_nino', models.AutoField(db_column='id_nino', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='fecha_nacimiento', null=True)),
                ('foto_url', models.CharField(blank=True, db_column='foto_url', max_length=300, null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.PROTECT, related_name='ninos', to='accounts.tutor')),
                ('modificado_por', models.ForeignKey(blank=True, db_column='modificado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nino',
                'indexes': [models.Index(fields=['id_tutor'], name='ix_nino_tutor')],
            },
        ),
    ]
