# Generated by Django 5.2.15 on 2026-07-07 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='centro',
            field=models.ForeignKey(
                blank=True,
                db_column='id_centro',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ninos',
                to='institutions.centroeducativo',
            ),
        ),
        migrations.AddIndex(
            model_name='nino',
            index=models.Index(fields=['centro'], name='ix_nino_centro'),
        ),
    ]
