# Generated by Django 5.2.15 on 2026-07-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_nino_centro'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='foto_public_id',
            field=models.CharField(
                blank=True,
                db_column='foto_public_id',
                max_length=255,
                null=True,
            ),
        ),
    ]
