# Generated by Django 5.2.15 on 2026-07-07 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.BigAutoField(db_column='id_bitacora', primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(db_column='tabla_afectada', max_length=100)),
                ('id_registro', models.CharField(db_column='id_registro', max_length=50)),
                ('operacion', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_column='operacion', max_length=10)),
                ('datos_anteriores', models.JSONField(blank=True, db_column='datos_anteriores', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, db_column='datos_nuevos', null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, db_column='fecha_evento')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, db_column='direccion_ip', null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora',
                'indexes': [models.Index(fields=['tabla_afectada', '-fecha_evento'], name='ix_bitacora_tabla_fecha')],
            },
        ),
    ]
