# Generated by Django 5.2.15 on 2026-07-07 14:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_tutor'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaSegura',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('id_zona', models.AutoField(db_column='id_zona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('poligono', django.contrib.gis.db.models.fields.PolygonField(db_column='poligono', geography=True, srid=4326)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_centro', models.ForeignKey(blank=True, db_column='id_centro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='institutions.centroeducativo')),
                ('id_tutor_propietario', models.ForeignKey(blank=True, db_column='id_tutor_propietario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='accounts.tutor')),
                ('modificado_por', models.ForeignKey(blank=True, db_column='modificado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zona_segura',
                'indexes': [models.Index(fields=['id_tutor_propietario'], name='ix_zona_tutor'), models.Index(fields=['id_centro'], name='ix_zona_centro')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('id_centro__isnull', True), ('id_tutor_propietario__isnull', False)), models.Q(('id_centro__isnull', False), ('id_tutor_propietario__isnull', True)), _connector='OR'), name='ck_zona_propietario_exclusivo')],
            },
        ),
    ]
