# Generated by Django 5.2.15 on 2026-07-07 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioZona',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('id_horario', models.AutoField(db_column='id_horario', primary_key=True, serialize=False)),
                ('dia_semana', models.SmallIntegerField(db_column='dia_semana')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('hora_fin', models.TimeField(db_column='hora_fin')),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='zones.zonasegura')),
                ('modificado_por', models.ForeignKey(blank=True, db_column='modificado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'horario_zona',
                'indexes': [models.Index(fields=['id_zona', 'dia_semana'], name='ix_horario_zona')],
                'constraints': [models.CheckConstraint(condition=models.Q(('dia_semana__gte', 1), ('dia_semana__lte', 7)), name='ck_horario_dia'), models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='ck_horario_horas')],
            },
        ),
        migrations.CreateModel(
            name='NinoZonaSegura',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('activa', models.BooleanField(db_column='activa', default=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='zonas_asociadas', to='children.nino')),
                ('id_zona', models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, related_name='ninos_asociados', to='zones.zonasegura')),
                ('modificado_por', models.ForeignKey(blank=True, db_column='modificado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nino_zona_segura',
                'constraints': [models.UniqueConstraint(fields=('id_nino', 'id_zona'), name='uq_nino_zona_segura')],
            },
        ),
    ]
